 
 
-- ----------------------------------------------------------------------------- 
------ 
--  Author        : aws-senior.com 
-- Description  : Displays information about temporary   tablespace   usage. 
--  Requirements  : Access to the DBA views. 
-- Call Syntax  : @temp_free_space 
-- ----------------------------------------------------------------------------- 
------ 
  SELECT   * 
FROM     dba  _temp_free_space; 
 
 
-------------------------------------------------------------------------------------- 
--  File Name     : https://github.com/Zaalouni/OracleDba  
--  Author        : Zaalouni 
--  website       : www.aws-senior.com 
-- Github       : https://github.com/Zaalouni/OracleDba 
-------------------------------------------------------------------------------------- 
  
