 
 
-- ----------------------------------------------------------------------------- 
------ 
--  Author        : aws-senior.com 
-- Description  : Compiles all invalid objects for specified schema, or all sche 
ma. 
--  Requirements  : Requires all other "Compile_All" scripts. 
-- Call Syntax  : @compile_all (schema-name or all) 
-- ----------------------------------------------------------------------------- 
------ 
@Compile_All_Specs &&1 
@Compile_All_Bodies &&1 
@Compile_All_Procs &&1 
@Compile_All_Funcs &&1 
@Compile_All_Views &&1 
 
 
-------------------------------------------------------------------------------------- 
--  File Name     : https://github.com/Zaalouni/OracleDba  
--  Author        : Zaalouni 
--  website       : www.aws-senior.com 
-- Github       : https://github.com/Zaalouni/OracleDba 
-------------------------------------------------------------------------------------- 
  
